package com.mest.hibernate.app.entity;

// default package
// Generated 2018-01-19 22:38:11 by Hibernate Tools 5.2.6.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Cennik generated by hbm2java
 */
public class Cennik implements java.io.Serializable {

	private Integer idProduktu;
	private String nazwa;
	private int cena;
	private String opis;
	private Set<Zakup> zakups = new HashSet<Zakup>(0);

	public Cennik() {
	}

	public Cennik(String nazwa, int cena, String opis) {
		this.nazwa = nazwa;
		this.cena = cena;
		this.opis = opis;
	}

	public Cennik(String nazwa, int cena, String opis, Set<Zakup> zakups) {
		this.nazwa = nazwa;
		this.cena = cena;
		this.opis = opis;
		this.zakups = zakups;
	}

	public Integer getIdProduktu() {
		return this.idProduktu;
	}

	public void setIdProduktu(Integer idProduktu) {
		this.idProduktu = idProduktu;
	}

	public String getNazwa() {
		return this.nazwa;
	}

	public void setNazwa(String nazwa) {
		this.nazwa = nazwa;
	}

	public int getCena() {
		return this.cena;
	}

	public void setCena(int cena) {
		this.cena = cena;
	}

	public String getOpis() {
		return this.opis;
	}

	public void setOpis(String opis) {
		this.opis = opis;
	}

	public Set<Zakup> getZakups() {
		return this.zakups;
	}

	public void setZakups(Set<Zakup> zakups) {
		this.zakups = zakups;
	}

}
