package com.mest.hibernate.app.entity;

import static javax.persistence.GenerationType.IDENTITY;

// default package
// Generated 2018-01-20 16:46:25 by Hibernate Tools 5.2.6.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.Proxy;

/**
 * Cennik generated by hbm2java
 */
@Entity
@Proxy(lazy=false)
@Table(name = "CENNIK", catalog = "ministrant_SBD")
public class Cennik implements java.io.Serializable {

	private Integer idProduktu;
	private String nazwa;
	private int cena;
	private String opis;
	private Set<Zakup> zakups = new HashSet<Zakup>(0);

	public Cennik() {
	}

	public Cennik(String nazwa, int cena, String opis) {
		this.nazwa = nazwa;
		this.cena = cena;
		this.opis = opis;
	}

	public Cennik(String nazwa, int cena, String opis, Set<Zakup> zakups) {
		this.nazwa = nazwa;
		this.cena = cena;
		this.opis = opis;
		this.zakups = zakups;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_produktu", unique = true, nullable = false)
	public Integer getIdProduktu() {
		return this.idProduktu;
	}

	public void setIdProduktu(Integer idProduktu) {
		this.idProduktu = idProduktu;
	}

	@Column(name = "nazwa", nullable = false, length = 20)
	public String getNazwa() {
		return this.nazwa;
	}

	public void setNazwa(String nazwa) {
		this.nazwa = nazwa;
	}

	@Column(name = "cena", nullable = false)
	public int getCena() {
		return this.cena;
	}

	public void setCena(int cena) {
		this.cena = cena;
	}

	@Column(name = "opis", nullable = false, length = 50)
	public String getOpis() {
		return this.opis;
	}

	public void setOpis(String opis) {
		this.opis = opis;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cennik")
	public Set<Zakup> getZakups() {
		return this.zakups;
	}

	public void setZakups(Set<Zakup> zakups) {
		this.zakups = zakups;
	}

	@Override
	public String toString() {
		return "Cennik [idProduktu=" + idProduktu + ", nazwa=" + nazwa + ", cena=" + cena + ", opis=" + opis + "]";
	}
 
}
