package com.mest.hibernate.app.entity;

// default package
// Generated 2018-01-20 16:46:25 by Hibernate Tools 5.2.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Kasa generated by hbm2java
 */
@Entity
@Table(name = "KASA", catalog = "ministrant_SBD")
public class Kasa implements java.io.Serializable {

	private Integer idZakupu;
	private Pracownik pracownik;
	private Date data;
	private Set<Zakup> zakups = new HashSet<Zakup>(0);

	public Kasa() {
	}

	public Kasa(Pracownik pracownik, Date data) {
		this.pracownik = pracownik;
		this.data = data;
	}

	public Kasa(Pracownik pracownik, Date data, Set<Zakup> zakups) {
		this.pracownik = pracownik;
		this.data = data;
		this.zakups = zakups;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_zakupu", unique = true, nullable = false)
	public Integer getIdZakupu() {
		return this.idZakupu;
	}

	public void setIdZakupu(Integer idZakupu) {
		this.idZakupu = idZakupu;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_pracownika", nullable = false)
	public Pracownik getPracownik() {
		return this.pracownik;
	}

	public void setPracownik(Pracownik pracownik) {
		this.pracownik = pracownik;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "data", nullable = false, length = 10)
	public Date getData() {
		return this.data;
	}

	public void setData(Date data) {
		this.data = data;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "kasa")
	public Set<Zakup> getZakups() {
		return this.zakups;
	}

	public void setZakups(Set<Zakup> zakups) {
		this.zakups = zakups;
	}

}
