package com.mest.hibernate.app.entity;

// default package
// Generated 2018-01-20 16:46:25 by Hibernate Tools 5.2.6.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PracZm generated by hbm2java
 */
@Entity
@Table(name = "PRAC_ZM", catalog = "ministrant_SBD")
public class PracZm implements java.io.Serializable {

	private PracZmId id;
	private Pracownik pracownik;
	private Zmiany zmiany;
	private Date data;

	public PracZm() {
	}

	public PracZm(PracZmId id, Pracownik pracownik, Zmiany zmiany) {
		this.id = id;
		this.pracownik = pracownik;
		this.zmiany = zmiany;
	}

	public PracZm(PracZmId id, Pracownik pracownik, Zmiany zmiany, Date data) {
		this.id = id;
		this.pracownik = pracownik;
		this.zmiany = zmiany;
		this.data = data;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idPracownika", column = @Column(name = "id_pracownika", nullable = false)),
			@AttributeOverride(name = "idZmiany", column = @Column(name = "id_zmiany", nullable = false)) })
	public PracZmId getId() {
		return this.id;
	}

	public void setId(PracZmId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_pracownika", nullable = false, insertable = false, updatable = false)
	public Pracownik getPracownik() {
		return this.pracownik;
	}

	public void setPracownik(Pracownik pracownik) {
		this.pracownik = pracownik;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_zmiany", nullable = false, insertable = false, updatable = false)
	public Zmiany getZmiany() {
		return this.zmiany;
	}

	public void setZmiany(Zmiany zmiany) {
		this.zmiany = zmiany;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "data", length = 10)
	public Date getData() {
		return this.data;
	}

	public void setData(Date data) {
		this.data = data;
	}

}
