package com.mest.hibernate.app.entity;

// default package
// Generated 2018-01-19 22:38:11 by Hibernate Tools 5.2.6.Final

import java.util.Date;

/**
 * PracZm generated by hbm2java
 */
public class PracZm implements java.io.Serializable {

	private PracZmId id;
	private Pracownik pracownik;
	private Zmiany zmiany;
	private Date data;

	public PracZm() {
	}

	public PracZm(PracZmId id, Pracownik pracownik, Zmiany zmiany) {
		this.id = id;
		this.pracownik = pracownik;
		this.zmiany = zmiany;
	}

	public PracZm(PracZmId id, Pracownik pracownik, Zmiany zmiany, Date data) {
		this.id = id;
		this.pracownik = pracownik;
		this.zmiany = zmiany;
		this.data = data;
	}

	public PracZmId getId() {
		return this.id;
	}

	public void setId(PracZmId id) {
		this.id = id;
	}

	public Pracownik getPracownik() {
		return this.pracownik;
	}

	public void setPracownik(Pracownik pracownik) {
		this.pracownik = pracownik;
	}

	public Zmiany getZmiany() {
		return this.zmiany;
	}

	public void setZmiany(Zmiany zmiany) {
		this.zmiany = zmiany;
	}

	public Date getData() {
		return this.data;
	}

	public void setData(Date data) {
		this.data = data;
	}

}
