package com.mest.hibernate.app.entity;

// default package
// Generated 2018-01-20 16:46:25 by Hibernate Tools 5.2.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pracownik generated by hbm2java
 */
@Entity
@Table(name = "PRACOWNIK", catalog = "ministrant_SBD")
public class Pracownik implements java.io.Serializable {

	private Integer idPracownika;
	private String imie;
	private String nazwisko;
	private Date dataZatrudnienia;
	private int pensja;
	private String stanowisko;
	private String kwalifikacje;
	private Set<Wybieg> wybiegs = new HashSet<Wybieg>(0);
	private Set<Zwierze> zwierzes = new HashSet<Zwierze>(0);
	private Set<PracZm> pracZms = new HashSet<PracZm>(0);
	private Set<Kasa> kasas = new HashSet<Kasa>(0);

	public Pracownik() {
	}

	public Pracownik(String imie, String nazwisko, Date dataZatrudnienia, int pensja, String stanowisko,
			String kwalifikacje) {
		this.imie = imie;
		this.nazwisko = nazwisko;
		this.dataZatrudnienia = dataZatrudnienia;
		this.pensja = pensja;
		this.stanowisko = stanowisko;
		this.kwalifikacje = kwalifikacje;
	}

	public Pracownik(String imie, String nazwisko, Date dataZatrudnienia, int pensja, String stanowisko,
			String kwalifikacje, Set<Wybieg> wybiegs, Set<Zwierze> zwierzes, Set<PracZm> pracZms, Set<Kasa> kasas) {
		this.imie = imie;
		this.nazwisko = nazwisko;
		this.dataZatrudnienia = dataZatrudnienia;
		this.pensja = pensja;
		this.stanowisko = stanowisko;
		this.kwalifikacje = kwalifikacje;
		this.wybiegs = wybiegs;
		this.zwierzes = zwierzes;
		this.pracZms = pracZms;
		this.kasas = kasas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_pracownika", unique = true, nullable = false)
	public Integer getIdPracownika() {
		return this.idPracownika;
	}

	public void setIdPracownika(Integer idPracownika) {
		this.idPracownika = idPracownika;
	}

	@Column(name = "imie", nullable = false, length = 20)
	public String getImie() {
		return this.imie;
	}

	public void setImie(String imie) {
		this.imie = imie;
	}

	@Column(name = "nazwisko", nullable = false, length = 20)
	public String getNazwisko() {
		return this.nazwisko;
	}

	public void setNazwisko(String nazwisko) {
		this.nazwisko = nazwisko;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "data_zatrudnienia", nullable = false, length = 10)
	public Date getDataZatrudnienia() {
		return this.dataZatrudnienia;
	}

	public void setDataZatrudnienia(Date dataZatrudnienia) {
		this.dataZatrudnienia = dataZatrudnienia;
	}

	@Column(name = "pensja", nullable = false)
	public int getPensja() {
		return this.pensja;
	}

	public void setPensja(int pensja) {
		this.pensja = pensja;
	}

	@Column(name = "stanowisko", nullable = false, length = 30)
	public String getStanowisko() {
		return this.stanowisko;
	}

	public void setStanowisko(String stanowisko) {
		this.stanowisko = stanowisko;
	}

	@Column(name = "kwalifikacje", nullable = false, length = 40)
	public String getKwalifikacje() {
		return this.kwalifikacje;
	}

	public void setKwalifikacje(String kwalifikacje) {
		this.kwalifikacje = kwalifikacje;
	}

	@ManyToMany(cascade = {CascadeType.ALL},fetch = FetchType.LAZY, mappedBy = "pracowniks")
	public Set<Wybieg> getWybiegs() {
		return this.wybiegs;
	}

	public void setWybiegs(Set<Wybieg> wybiegs) {
		this.wybiegs = wybiegs;
	}

	@ManyToMany(cascade = {CascadeType.ALL},fetch = FetchType.LAZY)
	@JoinTable(name = "TRESURA", catalog = "ministrant_SBD", joinColumns = {
			@JoinColumn(name = "id_pracownika", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "id_zwierzecia", nullable = false, updatable = false) })
	public Set<Zwierze> getZwierzes() {
		return this.zwierzes;
	}

	public void setZwierzes(Set<Zwierze> zwierzes) {
		this.zwierzes = zwierzes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pracownik")
	public Set<PracZm> getPracZms() {
		return this.pracZms;
	}

	public void setPracZms(Set<PracZm> pracZms) {
		this.pracZms = pracZms;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pracownik")
	public Set<Kasa> getKasas() {
		return this.kasas;
	}

	public void setKasas(Set<Kasa> kasas) {
		this.kasas = kasas;
	}

	@Override
	public String toString() {
		return "idPracownika=" + idPracownika + ", imie=" + imie + ", nazwisko=" + nazwisko
				+ ", dataZatrudnienia=" + dataZatrudnienia + ", pensja=" + pensja + ", stanowisko=" + stanowisko
				+ ", kwalifikacje=" + kwalifikacje;
	}

	
}
