package com.mest.hibernate.app.entity;

// default package
// Generated 2018-01-20 16:46:25 by Hibernate Tools 5.2.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PracZmId generated by hbm2java
 */
@Embeddable
public class PracZmId implements java.io.Serializable {

	private int idPracownika;
	private int idZmiany;

	public PracZmId() {
	}

	public PracZmId(int idPracownika, int idZmiany) {
		this.idPracownika = idPracownika;
		this.idZmiany = idZmiany;
	}

	@Column(name = "id_pracownika", nullable = false)
	public int getIdPracownika() {
		return this.idPracownika;
	}

	public void setIdPracownika(int idPracownika) {
		this.idPracownika = idPracownika;
	}

	@Column(name = "id_zmiany", nullable = false)
	public int getIdZmiany() {
		return this.idZmiany;
	}

	public void setIdZmiany(int idZmiany) {
		this.idZmiany = idZmiany;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PracZmId))
			return false;
		PracZmId castOther = (PracZmId) other;

		return (this.getIdPracownika() == castOther.getIdPracownika())
				&& (this.getIdZmiany() == castOther.getIdZmiany());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdPracownika();
		result = 37 * result + this.getIdZmiany();
		return result;
	}

}
