package com.mest.hibernate.app.entity;

// default package
// Generated 2018-01-19 22:38:11 by Hibernate Tools 5.2.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pracownik generated by hbm2java
 */
public class Pracownik implements java.io.Serializable {

	private Integer idPracownika;
	private String imie;
	private String nazwisko;
	private Date dataZatrudnienia;
	private int pensja;
	private String stanowisko;
	private String kwalifikacje;
	private Set<Wybieg> wybiegs = new HashSet<Wybieg>(0);
	private Set<Zwierze> zwierzes = new HashSet<Zwierze>(0);
	private Set<PracZm> pracZms = new HashSet<PracZm>(0);
	private Set<Kasa> kasas = new HashSet<Kasa>(0);

	public Pracownik() {
	}

	public Pracownik(String imie, String nazwisko, Date dataZatrudnienia, int pensja, String stanowisko,
			String kwalifikacje) {
		this.imie = imie;
		this.nazwisko = nazwisko;
		this.dataZatrudnienia = dataZatrudnienia;
		this.pensja = pensja;
		this.stanowisko = stanowisko;
		this.kwalifikacje = kwalifikacje;
	}

	public Pracownik(String imie, String nazwisko, Date dataZatrudnienia, int pensja, String stanowisko,
			String kwalifikacje, Set<Wybieg> wybiegs, Set<Zwierze> zwierzes, Set<PracZm> pracZms, Set<Kasa> kasas) {
		this.imie = imie;
		this.nazwisko = nazwisko;
		this.dataZatrudnienia = dataZatrudnienia;
		this.pensja = pensja;
		this.stanowisko = stanowisko;
		this.kwalifikacje = kwalifikacje;
		this.wybiegs = wybiegs;
		this.zwierzes = zwierzes;
		this.pracZms = pracZms;
		this.kasas = kasas;
	}

	public Integer getIdPracownika() {
		return this.idPracownika;
	}

	public void setIdPracownika(Integer idPracownika) {
		this.idPracownika = idPracownika;
	}

	public String getImie() {
		return this.imie;
	}

	public void setImie(String imie) {
		this.imie = imie;
	}

	public String getNazwisko() {
		return this.nazwisko;
	}

	public void setNazwisko(String nazwisko) {
		this.nazwisko = nazwisko;
	}

	public Date getDataZatrudnienia() {
		return this.dataZatrudnienia;
	}

	public void setDataZatrudnienia(Date dataZatrudnienia) {
		this.dataZatrudnienia = dataZatrudnienia;
	}

	public int getPensja() {
		return this.pensja;
	}

	public void setPensja(int pensja) {
		this.pensja = pensja;
	}

	public String getStanowisko() {
		return this.stanowisko;
	}

	public void setStanowisko(String stanowisko) {
		this.stanowisko = stanowisko;
	}

	public String getKwalifikacje() {
		return this.kwalifikacje;
	}

	public void setKwalifikacje(String kwalifikacje) {
		this.kwalifikacje = kwalifikacje;
	}

	public Set<Wybieg> getWybiegs() {
		return this.wybiegs;
	}

	public void setWybiegs(Set<Wybieg> wybiegs) {
		this.wybiegs = wybiegs;
	}

	public Set<Zwierze> getZwierzes() {
		return this.zwierzes;
	}

	public void setZwierzes(Set<Zwierze> zwierzes) {
		this.zwierzes = zwierzes;
	}

	public Set<PracZm> getPracZms() {
		return this.pracZms;
	}

	public void setPracZms(Set<PracZm> pracZms) {
		this.pracZms = pracZms;
	}

	public Set<Kasa> getKasas() {
		return this.kasas;
	}

	public void setKasas(Set<Kasa> kasas) {
		this.kasas = kasas;
	}

}
