package com.mest.hibernate.app.entity;

// default package
// Generated 2018-01-20 16:46:25 by Hibernate Tools 5.2.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Wybieg generated by hbm2java
 */
@Entity
@Table(name = "WYBIEG", catalog = "ministrant_SBD")
public class Wybieg implements java.io.Serializable {

	private Integer idWybiegu;
	private int temperatura;
	private int sektor;
	private String powierzchnia;
	private Set<Pracownik> pracowniks = new HashSet<Pracownik>(0);
	private Set<Zwierze> zwierzes = new HashSet<Zwierze>(0);

	public Wybieg() {
	}

	public Wybieg(int temperatura, int sektor, String powierzchnia) {
		this.temperatura = temperatura;
		this.sektor = sektor;
		this.powierzchnia = powierzchnia;
	}

	public Wybieg(int temperatura, int sektor, String powierzchnia, Set<Pracownik> pracowniks, Set<Zwierze> zwierzes) {
		this.temperatura = temperatura;
		this.sektor = sektor;
		this.powierzchnia = powierzchnia;
		this.pracowniks = pracowniks;
		this.zwierzes = zwierzes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_wybiegu", unique = true, nullable = false)
	public Integer getIdWybiegu() {
		return this.idWybiegu;
	}

	public void setIdWybiegu(Integer idWybiegu) {
		this.idWybiegu = idWybiegu;
	}

	@Column(name = "temperatura", nullable = false)
	public int getTemperatura() {
		return this.temperatura;
	}

	public void setTemperatura(int temperatura) {
		this.temperatura = temperatura;
	}

	@Column(name = "sektor", nullable = false)
	public int getSektor() {
		return this.sektor;
	}

	public void setSektor(int sektor) {
		this.sektor = sektor;
	}

	@Column(name = "powierzchnia", nullable = false, length = 20)
	public String getPowierzchnia() {
		return this.powierzchnia;
	}

	public void setPowierzchnia(String powierzchnia) {
		this.powierzchnia = powierzchnia;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "OPIEKA", catalog = "ministrant_SBD", joinColumns = {
			@JoinColumn(name = "id_wybiegu", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "id_pracownika", nullable = false, updatable = false) })
	public Set<Pracownik> getPracowniks() {
		return this.pracowniks;
	}

	public void setPracowniks(Set<Pracownik> pracowniks) {
		this.pracowniks = pracowniks;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "wybiegs")
	public Set<Zwierze> getZwierzes() {
		return this.zwierzes;
	}

	public void setZwierzes(Set<Zwierze> zwierzes) {
		this.zwierzes = zwierzes;
	}

}
