package com.mest.hibernate.app.entity;

// default package
// Generated 2018-01-19 22:38:11 by Hibernate Tools 5.2.6.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Wybieg generated by hbm2java
 */
public class Wybieg implements java.io.Serializable {

	private Integer idWybiegu;
	private int temperatura;
	private int sektor;
	private String powierzchnia;
	private Set<Pracownik> pracowniks = new HashSet<Pracownik>(0);
	private Set<Zwierze> zwierzes = new HashSet<Zwierze>(0);

	public Wybieg() {
	}

	public Wybieg(int temperatura, int sektor, String powierzchnia) {
		this.temperatura = temperatura;
		this.sektor = sektor;
		this.powierzchnia = powierzchnia;
	}

	public Wybieg(int temperatura, int sektor, String powierzchnia, Set<Pracownik> pracowniks, Set<Zwierze> zwierzes) {
		this.temperatura = temperatura;
		this.sektor = sektor;
		this.powierzchnia = powierzchnia;
		this.pracowniks = pracowniks;
		this.zwierzes = zwierzes;
	}

	public Integer getIdWybiegu() {
		return this.idWybiegu;
	}

	public void setIdWybiegu(Integer idWybiegu) {
		this.idWybiegu = idWybiegu;
	}

	public int getTemperatura() {
		return this.temperatura;
	}

	public void setTemperatura(int temperatura) {
		this.temperatura = temperatura;
	}

	public int getSektor() {
		return this.sektor;
	}

	public void setSektor(int sektor) {
		this.sektor = sektor;
	}

	public String getPowierzchnia() {
		return this.powierzchnia;
	}

	public void setPowierzchnia(String powierzchnia) {
		this.powierzchnia = powierzchnia;
	}

	public Set<Pracownik> getPracowniks() {
		return this.pracowniks;
	}

	public void setPracowniks(Set<Pracownik> pracowniks) {
		this.pracowniks = pracowniks;
	}

	public Set<Zwierze> getZwierzes() {
		return this.zwierzes;
	}

	public void setZwierzes(Set<Zwierze> zwierzes) {
		this.zwierzes = zwierzes;
	}

}
