package com.mest.hibernate.app.entity;

// default package
// Generated 2018-01-20 16:46:25 by Hibernate Tools 5.2.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Zakup generated by hbm2java
 */
@Entity
@Table(name = "ZAKUP", catalog = "ministrant_SBD")
public class Zakup implements java.io.Serializable {

	private ZakupId id;
	private Cennik cennik;
	private Kasa kasa;
	private int ilosc;

	public Zakup() {
	}

	public Zakup(ZakupId id, Cennik cennik, Kasa kasa, int ilosc) {
		this.id = id;
		this.cennik = cennik;
		this.kasa = kasa;
		this.ilosc = ilosc;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "idZakupu", column = @Column(name = "id_zakupu", nullable = false)),
			@AttributeOverride(name = "idProduktu", column = @Column(name = "id_produktu", nullable = false)) })
	public ZakupId getId() {
		return this.id;
	}

	public void setId(ZakupId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_produktu", nullable = false, insertable = false, updatable = false)
	public Cennik getCennik() {
		return this.cennik;
	}

	public void setCennik(Cennik cennik) {
		this.cennik = cennik;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_zakupu", nullable = false, insertable = false, updatable = false)
	public Kasa getKasa() {
		return this.kasa;
	}

	public void setKasa(Kasa kasa) {
		this.kasa = kasa;
	}

	@Column(name = "ilosc", nullable = false)
	public int getIlosc() {
		return this.ilosc;
	}

	public void setIlosc(int ilosc) {
		this.ilosc = ilosc;
	}

}
