package com.mest.hibernate.app.entity;

// default package
// Generated 2018-01-19 22:38:11 by Hibernate Tools 5.2.6.Final

/**
 * Zakup generated by hbm2java
 */
public class Zakup implements java.io.Serializable {

	private ZakupId id;
	private Cennik cennik;
	private Kasa kasa;
	private int ilosc;

	public Zakup() {
	}

	public Zakup(ZakupId id, Cennik cennik, Kasa kasa, int ilosc) {
		this.id = id;
		this.cennik = cennik;
		this.kasa = kasa;
		this.ilosc = ilosc;
	}

	public ZakupId getId() {
		return this.id;
	}

	public void setId(ZakupId id) {
		this.id = id;
	}

	public Cennik getCennik() {
		return this.cennik;
	}

	public void setCennik(Cennik cennik) {
		this.cennik = cennik;
	}

	public Kasa getKasa() {
		return this.kasa;
	}

	public void setKasa(Kasa kasa) {
		this.kasa = kasa;
	}

	public int getIlosc() {
		return this.ilosc;
	}

	public void setIlosc(int ilosc) {
		this.ilosc = ilosc;
	}

}
