package com.mest.hibernate.app.entity;

// default package
// Generated 2018-01-19 22:38:11 by Hibernate Tools 5.2.6.Final

/**
 * ZakupId generated by hbm2java
 */
public class ZakupId implements java.io.Serializable {

	private int idZakupu;
	private int idProduktu;

	public ZakupId() {
	}

	public ZakupId(int idZakupu, int idProduktu) {
		this.idZakupu = idZakupu;
		this.idProduktu = idProduktu;
	}

	public int getIdZakupu() {
		return this.idZakupu;
	}

	public void setIdZakupu(int idZakupu) {
		this.idZakupu = idZakupu;
	}

	public int getIdProduktu() {
		return this.idProduktu;
	}

	public void setIdProduktu(int idProduktu) {
		this.idProduktu = idProduktu;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ZakupId))
			return false;
		ZakupId castOther = (ZakupId) other;

		return (this.getIdZakupu() == castOther.getIdZakupu()) && (this.getIdProduktu() == castOther.getIdProduktu());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdZakupu();
		result = 37 * result + this.getIdProduktu();
		return result;
	}

}
