package com.mest.hibernate.app.entity;

// default package
// Generated 2018-01-19 22:38:11 by Hibernate Tools 5.2.6.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Zmiany generated by hbm2java
 */
public class Zmiany implements java.io.Serializable {

	private Integer idZmiany;
	private int godzinaOd;
	private int godzinaDo;
	private Set<PracZm> pracZms = new HashSet<PracZm>(0);

	public Zmiany() {
	}

	public Zmiany(int godzinaOd, int godzinaDo) {
		this.godzinaOd = godzinaOd;
		this.godzinaDo = godzinaDo;
	}

	public Zmiany(int godzinaOd, int godzinaDo, Set<PracZm> pracZms) {
		this.godzinaOd = godzinaOd;
		this.godzinaDo = godzinaDo;
		this.pracZms = pracZms;
	}

	public Integer getIdZmiany() {
		return this.idZmiany;
	}

	public void setIdZmiany(Integer idZmiany) {
		this.idZmiany = idZmiany;
	}

	public int getGodzinaOd() {
		return this.godzinaOd;
	}

	public void setGodzinaOd(int godzinaOd) {
		this.godzinaOd = godzinaOd;
	}

	public int getGodzinaDo() {
		return this.godzinaDo;
	}

	public void setGodzinaDo(int godzinaDo) {
		this.godzinaDo = godzinaDo;
	}

	public Set<PracZm> getPracZms() {
		return this.pracZms;
	}

	public void setPracZms(Set<PracZm> pracZms) {
		this.pracZms = pracZms;
	}

}
