package com.mest.hibernate.app.entity;

// default package
// Generated 2018-01-20 16:46:25 by Hibernate Tools 5.2.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Zmiany generated by hbm2java
 */
@Entity
@Table(name = "ZMIANY", catalog = "ministrant_SBD")
public class Zmiany implements java.io.Serializable {

	private Integer idZmiany;
	private int godzinaOd;
	private int godzinaDo;
	private Set<PracZm> pracZms = new HashSet<PracZm>(0);

	public Zmiany() {
	}

	public Zmiany(int godzinaOd, int godzinaDo) {
		this.godzinaOd = godzinaOd;
		this.godzinaDo = godzinaDo;
	}

	public Zmiany(int godzinaOd, int godzinaDo, Set<PracZm> pracZms) {
		this.godzinaOd = godzinaOd;
		this.godzinaDo = godzinaDo;
		this.pracZms = pracZms;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_zmiany", unique = true, nullable = false)
	public Integer getIdZmiany() {
		return this.idZmiany;
	}

	public void setIdZmiany(Integer idZmiany) {
		this.idZmiany = idZmiany;
	}

	@Column(name = "godzina_od", nullable = false)
	public int getGodzinaOd() {
		return this.godzinaOd;
	}

	public void setGodzinaOd(int godzinaOd) {
		this.godzinaOd = godzinaOd;
	}

	@Column(name = "godzina_do", nullable = false)
	public int getGodzinaDo() {
		return this.godzinaDo;
	}

	public void setGodzinaDo(int godzinaDo) {
		this.godzinaDo = godzinaDo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "zmiany")
	public Set<PracZm> getPracZms() {
		return this.pracZms;
	}

	public void setPracZms(Set<PracZm> pracZms) {
		this.pracZms = pracZms;
	}

}
